### ISSUE TITLE
undefined method `hash_key' for CanTango::Permits::UserPermit:Class

### ISSUE THREAD

**Issue by mattiassvedhem** [kristianmandrup/cantango#13]
When setting up an User with tango_user I get this error

```
undefined method `hash_key' for CanTango::Permits::UserPermit:Class
```

The subject looks like this:

```
#<CanTango::Configuration::HashRegistry:0x007f80463d1b48 @default=#<Hashie::Mash user=UserPermit>, @registered=#<Hashie::Mash user=UserPermit>>
```

Any ideas?

**Comment by kristianmandrup** [comment]
Well, if recently made the the Permit base class more generic in order to have a standard API so that you can register your own types of Permit classes, other than the 4 built-in ones, such as `RolePermit`. However, I only added the `#hash_key` class method to `RolePermit` and `RoleGroutPermit`. Now I've added `#hash_key` implementations to `UserPermit` and `AccountPermit` as well. Thanks for pointing out the bug! The fix should be in the latest push to master and the latest gem release. 
I've made a lot of changes to the internals lately but I really think and hope most of the bugs have been fixed now.
